
project: PairedImageSets
seed: 0  # random seed

data:
  name: PairedImageSets
  group1: "People wearing traditional Korean hanboks"
  group2: "People wearing traditional Japanese kimonos"
  purity: 1.0
